# Generated by Django 3.1.1 on 2020-11-07 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20201031_1438'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='post',
        ),
    ]
